---
- name: Update a Rails app
  hosts: rails_app_servers
  become: yes
  gather_facts: yes

  tasks:

  - block:
    - name: determine the branch that has been checked out
      shell: git status|head -1|cut -d" " -f3
      args:
        chdir: /home/{{ app }}/{{ app }}
      register: app_branch
      changed_when: false

    - name: update (git pull) app from git repo
      shell: 'git pull'
      args:
        chdir: '/home/{{ app }}/{{ app }}'
      register: git_pull
      when: app_branch.stdout == repo_branch|default('master')
      changed_when: git_pull.stdout != 'Already up to date.'
      notify: restart app

    - name: bundle install 
      shell: /home/{{ app }}/.rbenv/shims/bundle install
      args:
        chdir: /home/{{ app }}/{{ app }}
      register: bundle_install
      changed_when: bundle_install.stdout is search('Installing')
      failed_when: bundle_install.stdout is search('Could not')

    - name: bundle exec rake db:migrate
      shell: RAILS_ENV={{ rails_env|default('development') }} /home/{{ app }}/.rbenv/shims/bundle exec rake db:migrate
      args:
        chdir: /home/{{ app }}/{{ app }}
      register: db_migrate
      changed_when: db_migrate.stdout is search('migrating')
      failed_when: db_migrate.stdout is search('Error')
      notify: restart app
    - debug: var=db_migrate.stdout_lines

    - name: rake assets:precompile
      shell: RAILS_ENV={{ rails_env|default('development') }} /home/{{ app }}/.rbenv/shims/bundle exec rake assets:precompile
      args:
        chdir: /home/{{ app }}/{{ app }}
      register: rake_assets_precompile
      notify: restart app
    - debug: var=rake_assets_precompile.stderr_lines

    become: yes
    become_user: "{{ app }}"

    ### end of block

  handlers:
  - name: restart app
    systemd:
      name: '{{ app }}'
      state: restarted
